#!/bin/sh
if [[ $1 == "install" ]] || [[ $1 == "repl" ]] || [[ $1 == "--version" ]] || [[ $1 == "live" ]] || [[ $1 == "" ]]; then
    exec $(echo $0 | sed 's/-no-wire//') $@
else
    exec $(echo $0 | sed 's/-no-wire//') $@ --no-wire
fi
